apiVersion: apps/v1
kind: Deployment
metadata:
  name: osservice
spec:
  replicas: 1
  selector:
    matchLabels:
      app: osservice
  template:
    metadata:
      labels:
        app: osservice
    spec:
      containers:
      - name: osservice
        image: marciocardozodev/oficinacardozo-osservice:${IMAGE_TAG}
        ports:
        - containerPort: 80
        env:
        - name: ASPNETCORE_ENVIRONMENT
          valueFrom:
            configMapKeyRef:
              name: osservice-config
              key: ASPNETCORE_ENVIRONMENT
        - name: JWT_KEY
          valueFrom:
            secretKeyRef:
              name: osservice-secrets
              key: jwt-key
        volumeMounts:
        - name: cert-global-bundle-pe
          mountPath: /etc/ssl/certs/global-bundle.pem
          subPath: global-bundle.pem
        readinessProbe:
          httpGet:
            path: /health
            port: 80
          initialDelaySeconds: 5
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /health
            port: 80
          initialDelaySeconds: 15
          periodSeconds: 20
      volumes:
      - name: cert-global-bundle-pe
        configMap:
          name: cert-global-bundle-pe
