apiVersion: v1
kind: Secret
metadata:
  name: executionservice-db-secret
type: Opaque
stringData:
  DB_HOST: "<host_do_rds>"
  DB_USER: "<usuario>"
  DB_PASSWORD: "<senha>"
  DB_NAME: "executionservice"
