apiVersion: v1
kind: Secret
metadata:
  name: datadog-agent-secret
  namespace: default
  labels:
    app.kubernetes.io/instance: datadog-agent
    app.kubernetes.io/managed-by: datadog-operator
    app.kubernetes.io/name: datadog-agent-deployment
    app.kubernetes.io/part-of: default-datadog--agent
    app.kubernetes.io/version: ""
    operator.datadoghq.com/managed-by-dda-controller: "true"
    operator.datadoghq.com/managed-by-store: "true"
type: Opaque
data:
  api_key: ZDc2NGU0NThmNzJmZjc1ZjY0ZWNmMWY5NDRiNmQ4OWI=
  app_key: NGM4Zjc0OWNiNTA5M2I3YjgzNzYzMDBmZmJhZTZjYjk0MzFiZDMyNQ== # valor convertido para base64
