apiVersion: v1
kind: Secret
metadata:
  name: oficina-cardozo-db-secret
  labels:
    app: oficina-cardozo-api
stringData:
  ConnectionStrings__DefaultConnection: "Host=terraform-20260207150707457500000001.c3my46qic230.sa-east-1.rds.amazonaws.com;Port=5432;Database=oficinacardozo;Username=dbadmin;Password=Z4Zc7Xa5$&tz3mPMJ6qXPe#48szc5B%;SSL Mode=VerifyFull;Root Certificate=/certs/global-bundle.pe"
