apiVersion: v1
kind: Secret
metadata:
  name: oficina-cardozo-secrets
  labels:
    app: oficina-cardozo-api
type: Opaque
stringData:
  # Valores em texto puro; o Kubernetes converte para base64 internamente
  # Troque abaixo pela chave JWT real que vocÃª deseja usar em homolog
  CONFIGURACOESJWT__CHAVESECRETA: "ZnE1b0h0b3pNQXpmdGRsa2RTc2IyN3dueVJkaWtvQ3dQazFFenU2WEdBSHB1bE93QmpHTlBnU0Q5TXl5SU5WODlRendCQzFyb0tFcFVTUldBTWQ3bDBNRlFhVjVpc25pVVBXNUt2RmUxVnZlQ2JHU29Eazk5N29UczJWMFAwbjI"
  # Senha em texto puro do email
  CONFIGURACOESEMAIL__SENHA: "rvcb wcgg xnau inrz"
