name: CI/CD - App Kubernetes

on:
  pull_request:
    branches: [ develop, homolog, master ]

  push:
    branches: [ develop, homolog, master ]

env:
  DOTNET_VERSION: 8.0.x
  DOCKER_IMAGE: marciocardozodev/oficinacardozo-api-web

jobs:
  build-test-deploy:
    name: Build, Test & (Deploy if homolog/master)
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Exibir Dockerfile usado no build
      run: cat Dockerfile

    - name: Exibir entrypoint do Dockerfile
      run: grep ENTRYPOINT Dockerfile

    - name: Exibir arquivos publicados
      run: ls -lh /app/publish || true

    - name: Set deployment flag
      run: |
        if [ "${GITHUB_EVENT_NAME}" = "push" ] && { [ "${GITHUB_REF}" = "refs/heads/homolog" ] || [ "${GITHUB_REF}" = "refs/heads/master" ]; }; then
          echo "DEPLOY_ENABLED=true" >> "$GITHUB_ENV"
        else
          echo "DEPLOY_ENABLED=false" >> "$GITHUB_ENV"
        fi

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}

    - name: Cache NuGet packages
      uses: actions/cache@v3
      with:
        path: ~/.nuget/packages
        key: ${{ runner.os }}-nuget-${{ hashFiles('**/*.csproj') }}

    - name: Restore, Build & Test
      run: |
          dotnet restore OficinaCardozo.API/OficinaCardozo.API.csproj --verbosity minimal
          dotnet restore OficinaCardozo.Infrastructure/OficinaCardozo.Infrastructure.csproj --verbosity minimal
          dotnet restore OficinaCardozo.Application/OficinaCardozo.Application.csproj --verbosity minimal
          dotnet restore OficinaCardozo.Domain/OficinaCardozo.Domain.csproj --verbosity minimal
          dotnet restore OficinaCardozo.Tests/OficinaCardozo.Tests.csproj --verbosity minimal
          dotnet build OficinaCardozo.API/OficinaCardozo.API.csproj --no-restore --configuration Release --verbosity minimal
          dotnet build OficinaCardozo.Infrastructure/OficinaCardozo.Infrastructure.csproj --no-restore --configuration Release --verbosity minimal
          dotnet build OficinaCardozo.Application/OficinaCardozo.Application.csproj --no-restore --configuration Release --verbosity minimal
          dotnet build OficinaCardozo.Domain/OficinaCardozo.Domain.csproj --no-restore --configuration Release --verbosity minimal
          dotnet build OficinaCardozo.Tests/OficinaCardozo.Tests.csproj --no-restore --configuration Release --verbosity minimal
          dotnet test OficinaCardozo.Tests/OficinaCardozo.Tests.csproj --no-build --configuration Release --verbosity minimal --logger "console;verbosity=minimal"

    - name: Docker login
      if: env.DEPLOY_ENABLED == 'true'
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and push Docker image
      if: env.DEPLOY_ENABLED == 'true'
      run: |
        TAG="manual-$(date +%Y%m%d%H%M%S)"
        echo "TAG=$TAG" >> $GITHUB_ENV
        docker build -t $DOCKER_IMAGE:$TAG -f Dockerfile .
        docker push $DOCKER_IMAGE:$TAG

    - name: Atualizar deployment.yaml com nova tag
      if: env.DEPLOY_ENABLED == 'true'
      run: |
        sed -i "s|image: $DOCKER_IMAGE:.*|image: $DOCKER_IMAGE:$TAG|g" k8s/deployment.yaml
        git config --global user.email "github-actions@github.com"
        git config --global user.name "github-actions"
        git add k8s/deployment.yaml
        git commit -m "ci: update deployment image tag to $TAG" || echo "No changes to commit"
        git push || echo "No changes to push"

    - name: Configure AWS credentials for EKS
      if: env.DEPLOY_ENABLED == 'true'
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1



    - name: Baixar tfstate do S3
      if: env.DEPLOY_ENABLED == 'true'
      run: aws s3 cp s3://oficina-cardozo-terraform-state/eks/prod/terraform.tfstate terraform.tfstate

    - name: Gerar kubeconfig do EKS
      if: env.DEPLOY_ENABLED == 'true'
      run: |
        export CLUSTER_NAME="oficina-cardozo-eks"
        export AWS_REGION="us-east-1"
        aws eks update-kubeconfig --region "$AWS_REGION" --name "$CLUSTER_NAME"


    - name: Apply manifests to Kubernetes
      if: env.DEPLOY_ENABLED == 'true'
      run: |
        if [ "${GITHUB_REF}" = "refs/heads/master" ]; then
          NAMESPACE="${K8S_NAMESPACE_PROD}"
        else
          NAMESPACE="${K8S_NAMESPACE_HOMOLOG}"
        fi

        kubectl -n "$NAMESPACE" apply -f k8s/

        kubectl -n "$NAMESPACE" set image deployment/oficina-cardozo-api \
          api=$DOCKER_IMAGE:$TAG

        kubectl -n "$NAMESPACE" rollout status deployment/oficina-cardozo-api
      env:
        K8S_NAMESPACE_HOMOLOG: oficina-homolog
        K8S_NAMESPACE_PROD: oficina-prod