name: CI/CD - App Kubernetes

on:
  pull_request:
    branches: [ develop, homolog, master ]

  push:
    branches: [ develop, homolog, master ]

env:
  DOTNET_VERSION: 8.0.x
  DOCKER_IMAGE: marciocardozodev/oficinacardozo-api

jobs:
  build-test-deploy:
    name: Build, Test & (Deploy if homolog/master)
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Set deployment flag
      run: |
        if [ "${GITHUB_EVENT_NAME}" = "push" ] && { [ "${GITHUB_REF}" = "refs/heads/homolog" ] || [ "${GITHUB_REF}" = "refs/heads/master" ]; }; then
          echo "DEPLOY_ENABLED=true" >> "$GITHUB_ENV"
        else
          echo "DEPLOY_ENABLED=false" >> "$GITHUB_ENV"
        fi

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}

    - name: Cache NuGet packages
      uses: actions/cache@v3
      with:
        path: ~/.nuget/packages
        key: ${{ runner.os }}-nuget-${{ hashFiles('**/*.csproj') }}

    - name: Restore, Build & Test
      run: |
          dotnet restore OficinaCardozo.API/OficinaCardozo.API.csproj --verbosity minimal
          dotnet restore OficinaCardozo.Infrastructure/OficinaCardozo.Infrastructure.csproj --verbosity minimal
          dotnet restore OficinaCardozo.Application/OficinaCardozo.Application.csproj --verbosity minimal
          dotnet restore OficinaCardozo.Domain/OficinaCardozo.Domain.csproj --verbosity minimal
          dotnet restore OficinaCardozo.Tests/OficinaCardozo.Tests.csproj --verbosity minimal
          dotnet build OficinaCardozo.API/OficinaCardozo.API.csproj --no-restore --configuration Release --verbosity minimal
          dotnet build OficinaCardozo.Infrastructure/OficinaCardozo.Infrastructure.csproj --no-restore --configuration Release --verbosity minimal
          dotnet build OficinaCardozo.Application/OficinaCardozo.Application.csproj --no-restore --configuration Release --verbosity minimal
          dotnet build OficinaCardozo.Domain/OficinaCardozo.Domain.csproj --no-restore --configuration Release --verbosity minimal
          dotnet build OficinaCardozo.Tests/OficinaCardozo.Tests.csproj --no-restore --configuration Release --verbosity minimal
          dotnet test OficinaCardozo.Tests/OficinaCardozo.Tests.csproj --no-build --configuration Release --verbosity minimal --logger "console;verbosity=minimal"

    - name: Docker login
      if: env.DEPLOY_ENABLED == 'true'
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and push Docker image
      if: env.DEPLOY_ENABLED == 'true'
      run: |
        SHORT_SHA=${GITHUB_SHA::7}
        if [ "${GITHUB_REF}" = "refs/heads/master" ]; then
          TAG="${SHORT_SHA}"
        else
          TAG="homolog-${SHORT_SHA}"
        fi

        docker build -t $DOCKER_IMAGE:$TAG -f Dockerfile .
        docker push $DOCKER_IMAGE:$TAG

    - name: Configure AWS credentials for EKS
      if: env.DEPLOY_ENABLED == 'true'
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1

    - name: Configure kubectl
      if: env.DEPLOY_ENABLED == 'true'
      run: |
        mkdir -p $HOME/.kube
        echo "${KUBE_CONFIG}" > $HOME/.kube/config
      env:
        KUBE_CONFIG: ${{ secrets.KUBE_CONFIG_HOMOLOG_PROD }}

    - name: Executar migrations EF Core no RDS
      if: env.DEPLOY_ENABLED == 'true'
      run: |
        sudo apt-get update && sudo apt-get install -y postgresql-client
        export PGPASSWORD='Z4Zc7Xa5$&tz3mPMJ6qXPe#48szc5B%'
        psql -h oficina-cardozo-db.celegsiik31m.us-east-1.rds.amazonaws.com -U dbadmin -d oficinacardozo -c '\l'
        dotnet tool install --global dotnet-ef --version 8.0.11
        export PATH="$PATH:/home/vscode/.dotnet/tools"
        dotnet restore OficinaCardozo.Infrastructure/OficinaCardozo.Infrastructure.csproj
        dotnet restore OficinaCardozo.API/OficinaCardozo.API.csproj
        dotnet ef database update --project OficinaCardozo.Infrastructure/OficinaCardozo.Infrastructure.csproj --startup-project OficinaCardozo.API/OficinaCardozo.API.csproj
      env:
        CONFIGURACOESJWT__CHAVESECRETA: "ZnE1b0h0b3pNQXpmdGRsa2RTc2IyN3dueVJkaWtvQ3dQazFFenU2WEdBSHB1bE93QmpHTlBnU0Q5TXl5SU5WODlRendCQzFyb0tFcFVTUldBTWQ3bDBNRlFhVjVpc25pVVBXNUt2RmUxVnZlQ2JHU29Eazk5N29UczJWMFAwbjI"
        ASPNETCORE_ENVIRONMENT: "Production"
        ConnectionStrings__DefaultConnection: "Host=oficina-cardozo-db.celegsiik31m.us-east-1.rds.amazonaws.com;Port=5432;Database=oficinacardozo;Username=dbadmin;Password=Z4Zc7Xa5$&tz3mPMJ6qXPe#48szc5B%;Ssl Mode=Require;Trust Server Certificate=true;"

    - name: Apply manifests to Kubernetes
      if: env.DEPLOY_ENABLED == 'true'
      run: |
        SHORT_SHA=${GITHUB_SHA::7}
        if [ "${GITHUB_REF}" = "refs/heads/master" ]; then
          NAMESPACE="${K8S_NAMESPACE_PROD}"
          TAG="${SHORT_SHA}"
        else
          NAMESPACE="${K8S_NAMESPACE_HOMOLOG}"
          TAG="homolog-${SHORT_SHA}"
        fi

        kubectl -n "$NAMESPACE" apply -f k8s/

        kubectl -n "$NAMESPACE" set image deployment/oficina-cardozo-api \
          api=$DOCKER_IMAGE:$TAG

        kubectl -n "$NAMESPACE" rollout status deployment/oficina-cardozo-api
      env:
        K8S_NAMESPACE_HOMOLOG: ${{ secrets.K8S_NAMESPACE_HOMOLOG }}
        K8S_NAMESPACE_PROD: ${{ secrets.K8S_NAMESPACE_PROD }}